# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apigateway-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e2db0e4d6c34b68b8c3539cbc9c857a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b221e045b46c47e8a3d4d3e2e2a7d970 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e2db0e4d6c34b68b8c3539cbc9c857a }}/gateway-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apigateway-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fe2306b5c6c74c9481a0c9528bf5b361 }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e2db0e4d6c34b68b8c3539cbc9c857a }}/gateway-server:${{ github.sha }}'